# Generated by Django 4.1.4 on 2023-02-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
